[package]
name = "gleif-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0"
thiserror = "2.0.12"
reqwest = { version = "0.12", features = ["json"] }
reqwest-middleware = "0.4.2"
futures-core = "0.3"
futures-util = "0.3"

[dev-dependencies]
reqwest-retry = "0.7"
