[package]
name = "gleif-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
reqwest = { version = "0.12.15", features = ["json"] }
reqwest-middleware = "0.4.2"
url = "2.5.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
futures-core = "0.3.31"
futures-util = "0.3.31"

[dev-dependencies]
reqwest-retry = "0.7"
